name: Frontend Linter

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  frontend-linter:
    name: HTML, CSS, & JS Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run HTML Lint
        run: npx htmlhint "**/*.html"

      - name: Run CSS Lint
        run: npx stylelint "**/*.css"

      - name: Run JS Lint
        run: npx eslint "**/*.js"